# Generated by Django 5.2.3 on 2025-06-18 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="board",
            name="writer",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
