# Generated by Django 5.2.3 on 2025-06-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="in_business",
            field=models.BooleanField(default=False),
        ),
    ]
